export const FISCAL_DESK_DISABLE_COMPLETION_DIALOG_ENV =
  "FISCAL_DESK_DISABLE_COMPLETION_DIALOG";
export const FISCAL_DESK_DISABLE_DEVTOOLS_ENV = "FISCAL_DESK_DISABLE_DEVTOOLS";
export const FISCAL_DESK_DEV_SERVER_URL_ENV = "FISCAL_DESK_DEV_SERVER_URL";
export const FISCAL_DESK_USER_DATA_DIR_ENV = "FISCAL_DESK_USER_DATA_DIR";
